apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-inventory-database-dev-pv
  namespace: inventorytracker-api-dev
  labels:
    app: inventorytool-v2
    component: backend
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/inventorytool-v2/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-inventory-database-dev-pvc
  namespace: inventorytracker-api-dev
  labels:
    app: inventorytool-v2
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
