apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventorytool-v2-frontend
  namespace: inventorytracker-api-dev
  labels:
    app: inventorytool-v2
    component: frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: inventorytool-v2-dev.ccm-gke-ddtc-riselab-np-b.p3-np.cox.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventorytool-v2-frontend
                port:
                  number: 80
